name: Java CI with Gradle
on:
  push:
    branches: [ "kurtsevaVa" ] 
  pull_request:
    branches: [ "kurtsevaVa" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Make gradlew executable
        run: chmod +x gradlew  
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Build with Gradle
        run: ./gradlew build
